name: Playwrihght Tets
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - run: npm ci

      - run: npx playwright install --with-deps

      - run: npx playwright
