name: Playwrihght Tets
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name : Build Dcoker image
        run:  docker build -t project-poc-playwright .

      - name: Run Smoke Tests
        run: docker run --rm project-poc-playwright npm run test:qa -- --grep "@smoke"

      # - uses: actions/setup-node@v6
      #   with:
      #     node-version: lts/*

      # - run: npm ci

      # - run: npx playwright install --with-deps

      # - run: npm run test:qa -- --grep "@smoke"    
